# 1. Base image
FROM node:20-alpine

# 2. Set working directory inside container
WORKDIR /app

# 3. Copy package files first (for caching)
COPY package*.json ./

# 4. Install dependencies
RUN npm install --production

# 5. Copy rest of the code
COPY . .

# 6. Expose port
EXPOSE 5000

# 7. Start server
CMD ["node", "index.js"]
